spring:
  application:
    name: api-gateway
  profiles:
    active: prod

app:
  redis:
    startup-check:
      enabled: true

rate-limiter:
  enabled: true
  bucket:
    key: ${ADMISSION_BUCKET_KEY:admission}
    capacity: ${ADMISSION_BUCKET_CAPACITY:300}
    refill-token-amount: ${ADMISSION_BUCKET_REFILL_AMOUNT:30}
    refill-interval-seconds: ${ADMISSION_BUCKET_REFILL_INTERVAL_SECONDS:1}
    redirect-threshold: ${ADMISSION_BUCKET_REDIRECT_THRESHOLD:2}
    rejection-cooldown-millis: ${ADMISSION_BUCKET_REJECTION_COOLDOWN_MILLIS:-1}
    max-in-flight-checks: ${ADMISSION_BUCKET_MAX_IN_FLIGHT_CHECKS:100}

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - name: api-service-route
              uri: lb://api-service
              predicates:
                - Path=/api/v1/**
              filters:
                - name: RateLimiter
            - name: turnstile-route
              uri: http://turnstile:8080
              predicates:
                - Path=/turnstile/**, /.well-known/openid-configuration
    discovery:
      client:
        simple:
          instances:
            api-service:
              - uri: http://app1:8080
              - uri: http://app2:8080
custom:
  auth:
    jwk-set-uri: http://turnstile:8080/.well-known/openid-configuration

---
server:
  port: 8079

spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - name: api-service-route
              uri: lb://api-service
              predicates:
                - Path=/api/v1/**
              filters:
                - name: RateLimiter
            - name: turnstile-route
              uri: http://localhost:8083
              predicates:
                - Path=/turnstile/**, /.well-known/openid-configuration
    discovery:
      client:
        simple:
          instances:
            api-service:
              - uri: http://localhost:8081
              - uri: http://localhost:8082

custom:
  auth:
    jwk-set-uri: http://localhost:8080/.well-known/openid-configuration
